version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: train-tech-assist-bot
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge